In [2]:
import numpy as np
import pandas as pd

In [3]:
np.__version__

'1.20.1'

In [4]:
pd.__version__

'1.2.4'

In [5]:
df = pd.read_csv('hw-1.csv')

In [6]:
df.head(2)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650

#### Answer 3

In [7]:
#avg price of BMW
df.groupby('Make').MSRP.mean()['BMW']

61546.76347305389

### Ans 4
### Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

In [8]:
df[df.Year >= 2015]['Engine HP'].isnull().sum()

51

In [9]:
df[
    (df['Year'] >= 2015) 
]

Make       Model  Year                Engine Fuel Type  Engine HP  \
32     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
33     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
34     FIAT  124 Spider  2017  premium unleaded (recommended)      160.0   
41      BMW    2 Series  2016     premium unleaded (required)      240.0   
42      BMW    2 Series  2016     premium unleaded (required)      240.0   
...     ...         ...   ...                             ...        ...   
11898   BMW          Z4  2015     premium unleaded (required)      300.0   
11899   BMW          Z4  2015     premium unleaded (required)      335.0   
11900   BMW          Z4  2016     premium unleaded (required)      300.0   
11901   BMW          Z4  2016     premium unleaded (required)      240.0   
11902   BMW          Z4  2016     premium unleaded (required)      335.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
32                  4.0            MANUAL  rear wheel drive              2.0   
33                  4.0            MANUAL  rear wheel drive              2.0   
34                  4.0            MANUAL  rear wheel drive              2.0   
41                  4.0         AUTOMATIC  rear wheel drive              2.0   
42                  4.0         AUTOMATIC  rear wheel drive              2.0   
...                 ...               ...               ...              ...   
11898               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11899               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11900               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   
11901               4.0            MANUAL  rear wheel drive              2.0   
11902               6.0  AUTOMATED_MANUAL  rear wheel drive              2.0   

               Market Category Vehicle Size Vehicle Style  highway MPG  \
32                 Performance      Compact   Convertible           35   
33                 Performance      Compact   Convertible           35   
34                 Performance      Compact   Convertible           35   
41          Luxury,Performance      Compact         Coupe           35   
42                      Luxury      Compact   Convertible           34   
...                        ...          ...           ...          ...   
11898  Luxury,High-Performance      Compact   Convertible           24   
11899  Luxury,High-Performance      Compact   Convertible           24   
11900  Luxury,High-Performance      Compact   Convertible           24   
11901       Luxury,Performance      Compact   Convertible           34   
11902  Luxury,High-Performance      Compact   Convertible           24   

       city mpg  Popularity   MSRP  
32           26         819  27495  
33           26         819  24995  
34           26         819  28195  
41           23        3916  32850  
42           23        3916  38650  
...         ...         ...    ...  
11898        17        3916  56950  
11899        17        3916  65800  
11900        17        3916  57500  
11901        22        3916  49700  
11902        17        3916  66350  

[5995 rows x 16 columns]

In [10]:
df[
    (df['Year'] >= 2015) 
].describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  5995.000000  5944.000000       5987.000000      5990.000000   
mean   2015.916264   272.987719          5.437281         3.600000   
std       0.795798   109.117257          1.718261         0.789774   
min    2015.000000    66.000000          0.000000         2.000000   
25%    2015.000000   184.000000          4.000000         4.000000   
50%    2016.000000   270.000000          6.000000         4.000000   
75%    2017.000000   325.000000          6.000000         4.000000   
max    2017.000000   750.000000         12.000000         4.000000   

       highway MPG     city mpg   Popularity           MSRP  
count  5995.000000  5995.000000  5995.000000    5995.000000  
mean     28.955129    21.526105  1758.674562   45667.156464  
std      10.088488    10.505942  1442.645543   40051.192137  
min      13.000000    10.000000    21.000000   11990.000000  
25%      24.000000    17.000000   640.000000   26910.000000  
50%      28.000000    20.000000  1439.000000   35845.000000  
75%      33.000000    24.000000  2031.000000   48105.000000  
max     354.000000   137.000000  5657.000000  548800.000000

In [11]:
df[
    (df['Year'] >= 2015) & (df['Engine HP'].isnull())
].describe()

Year  Engine HP  Engine Cylinders  Number of Doors  highway MPG  \
count    51.0        0.0         51.000000        46.000000    51.000000   
mean   2016.0        NaN          1.882353         3.869565    73.313725   
std       0.8        NaN          2.542810         0.499275    34.854262   
min    2015.0        NaN          0.000000         2.000000    25.000000   
25%    2015.0        NaN          0.000000         4.000000    29.500000   
50%    2016.0        NaN          0.000000         4.000000    92.000000   
75%    2017.0        NaN          4.000000         4.000000   101.000000   
max    2017.0        NaN          6.000000         4.000000   108.000000   

         city mpg  Popularity           MSRP  
count   51.000000    51.00000      51.000000  
mean    77.607843  1835.45098   50249.313725  
std     43.784965  1650.84002   25001.993781  
min     17.000000    61.00000   25100.000000  
25%     22.500000  1385.00000   31975.000000  
50%     95.000000  1391.00000   37570.000000  
75%    120.000000  2009.00000   67950.000000  
max    126.000000  5657.00000  134500.000000

In [12]:
df[
    (df['Year'] >= 2015) & ['Engine HP']
].isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

### Ans 5

In [13]:
df['Engine HP'].mean()

249.38607007176023

In [14]:
#Calculate the average "Engine HP" in the dataset
#df.head(2)
df['Engine HP'].mean()

249.38607007176023

In [15]:
# Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.

In [16]:
df['Engine HP'].fillna(df['Engine HP'].mean()).mean()

249.38607007176

In [17]:
df['Engine HP'].fillna(0).mean()

247.94174920261878

### Ans 6

In [18]:
# Select all the "Rolls-Royce" cars from the dataset

df.head(2)

df_rr = df[
    df['Make'] == 'Rolls-Royce'
]

df_rr.head(2)

Make     Model  Year             Engine Fuel Type  Engine HP  \
2921  Rolls-Royce  Corniche  2001  premium unleaded (required)      325.0   
3505  Rolls-Royce      Dawn  2016  premium unleaded (required)      563.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
2921               8.0         AUTOMATIC  rear wheel drive              2.0   
3505              12.0         AUTOMATIC  rear wheel drive              2.0   

                     Market Category Vehicle Size Vehicle Style  highway MPG  \
2921                   Exotic,Luxury        Large   Convertible           15   
3505  Exotic,Luxury,High-Performance        Large   Convertible           19   

      city mpg  Popularity    MSRP  
2921        10          86  359990  
3505        12          86  335000

In [19]:
# Select only columns "Engine HP", "Engine Cylinders", "highway MPG".

df_rr = df_rr[['Engine HP','Engine Cylinders','highway MPG']]
df_rr.head(2)

Engine HP  Engine Cylinders  highway MPG
2921      325.0               8.0           15
3505      563.0              12.0           19

In [20]:
# Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).

df_rr = df_rr.drop_duplicates()
df_rr

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [21]:
X = df_rr.values
print(X)

[[325.   8.  15.]
 [563.  12.  19.]
 [563.  12.  21.]
 [563.  12.  20.]
 [322.  12.  15.]
 [453.  12.  19.]
 [624.  12.  21.]]


In [22]:
# X times transpose of X
XTX = X.T.dot(X)
print(XTX)

[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]


In [23]:
#invert XTX
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv.shape)

(3, 3)


In [24]:
XTX_inv.sum()

0.032212320677486195

## Answer 7

In [25]:
# create an array
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])
print(y)


[1000 1100  900 1200 1000  850 1300]


In [27]:
z = XTX_inv.dot(X.T)
w = z.dot(y)


In [28]:
w

array([ 0.19989598, 31.02612262, 31.65378877])